---
apiVersion: v1
kind: ImageStream
metadata:
  name: s2i-webpacker-builder
  labels:
    app: s2i-webpacker-builder
spec:
  tags:
  - name: latest
    from:
      kind: DockerImage
      name: blockfin/s2i-webpacker:1.0.0
